// From AnalogSense.js
const keyMapping = [
  { name: "Escape", value: 0x29 },
  { name: "F1", value: 0x3A },
  { name: "F2", value: 0x3B },
  { name: "F3", value: 0x3C },
  { name: "F4", value: 0x3D },
  { name: "F5", value: 0x3E },
  { name: "F6", value: 0x3F },
  { name: "F7", value: 0x40 },
  { name: "F8", value: 0x41 },
  { name: "F9", value: 0x42 },
  { name: "F10", value: 0x43 },
  { name: "F11", value: 0x44 },
  { name: "F12", value: 0x45 },
  { name: "`", value: 0x35 },
  { name: "1", value: 0x1E },
  { name: "2", value: 0x1F },
  { name: "3", value: 0x20 },
  { name: "4", value: 0x21 },
  { name: "5", value: 0x22 },
  { name: "6", value: 0x23 },
  { name: "7", value: 0x24 },
  { name: "8", value: 0x25 },
  { name: "9", value: 0x26 },
  { name: "0", value: 0x27 },
  { name: "-", value: 0x2D },
  { name: "=", value: 0x2E },
  { name: "Backspace", value: 0x2A, },
  { name: "Tab", value: 0x2B },
  { name: "Q", value: 0x14 },
  { name: "W", value: 0x1A },
  { name: "E", value: 0x08 },
  { name: "R", value: 0x15 },
  { name: "T", value: 0x17 },
  { name: "Y", value: 0x1C },
  { name: "U", value: 0x18 },
  { name: "I", value: 0x0C },
  { name: "O", value: 0x12 },
  { name: "P", value: 0x13 },
  { name: "[", value: 0x2F },
  { name: "]", value: 0x30 },
  { name: "Enter", value: 0x28 },
  { name: "Caps Lock", value: 0x39 },
  { name: "A", value: 0x04 },
  { name: "S", value: 0x16 },
  { name: "D", value: 0x07 },
  { name: "F", value: 0x09 },
  { name: "G", value: 0x0A },
  { name: "H", value: 0x0B },
  { name: "J", value: 0x0D },
  { name: "K", value: 0x0E },
  { name: "L", value: 0x0F },
  { name: ";", value: 0x33 },
  { name: "'", value: 0x34 },
  { name: "Backslash", value: 0x31 },
  { name: "Left Shift", value: 0xE1 },
  { name: "Intl Backslash", value: 0x64 },
  { name: "Z", value: 0x1D },
  { name: "X", value: 0x1B },
  { name: "C", value: 0x06 },
  { name: "V", value: 0x19 },
  { name: "B", value: 0x05 },
  { name: "N", value: 0x11 },
  { name: "M", value: 0x10 },
  { name: ",", value: 0x36 },
  { name: ".", value: 0x37 },
  { name: "/", value: 0x38 },
  { name: "Right Shift", value: 0xE5 },
  { name: "Left Ctrl", value: 0xE0 },
  { name: "Left Meta", value: 0xE3 },
  { name: "Left Alt", value: 0xE2 },
  { name: "Space", value: 0x2C },
  { name: "Right Alt", value: 0xE6 },
  { name: "Right Meta", value: 0xE7 },
  { name: "Fn", value: 0x409 },
  { name: "Context Menu", value: 0x65 },
  { name: "Right Ctrl", value: 0xE4 },
  { name: "Print Screen", value: 0x46 },
  { name: "Pause", value: 0x48 },
  { name: "Scroll Lock", value: 0x47 },
  { name: "Insert", value: 0x49 },
  { name: "Home", value: 0x4A },
  { name: "Page Up", value: 0x4B },
  { name: "Delete", value: 0x4C },
  { name: "End", value: 0x4D },
  { name: "Page Down", value: 0x4E },
  { name: "Up Arrow", value: 0x52 },
  { name: "Left Arrow", value: 0x50 },
  { name: "Down Arrow", value: 0x51 },
  { name: "Right Arrow", value: 0x4F },
  { name: "Num Lock", value: 0x53 },
  { name: "Numpad /", value: 0x54 },
  { name: "Numpad *", value: 0x55 },
  { name: "Numpad -", value: 0x56 },
  { name: "Numpad 7", value: 0x5F },
  { name: "Numpad 8", value: 0x60 },
  { name: "Numpad 9", value: 0x61 },
  { name: "Numpad +", value: 0x57 },
  { name: "Numpad 4", value: 0x5C },
  { name: "Numpad 5", value: 0x5D },
  { name: "Numpad 6", value: 0x5E },
  { name: "Numpad 1", value: 0x59 },
  { name: "Numpad 2", value: 0x5A },
  { name: "Numpad 3", value: 0x5B },
  { name: "Numpad Enter", value: 0x58 },
  { name: "Numpad 0", value: 0x62 },
  { name: "Numpad .", value: 0x63 }
];

export const keyCodeToName = new Map<number, string>();
for (const k of keyMapping) {
  keyCodeToName.set(k.value, k.name);
}
